namespace Peerly.Gateway.Api.Infrastructure;

public enum ApiPermission
{
    GenerateUploadUrl = 1,
    Logout = 2,
    ListCourses = 3,
    CreateCourse = 4,
    GetStudentCourse = 5,
    UpdateCourse = 6,
    ListCourseParticipants = 7,
    DeleteCourse = 8,
    DeleteGroup = 9,
    ListGroupParticipants = 10,
    ListStudentCourses = 11,
    ListTeacherCourses = 12,
    GetTeacherCourse = 13,
    GenerateDownloadUrl = 14,
    CreateHomeworkFile = 15,
    CreateSubmittedHomework = 16,
    GetTeacherGroup = 17,
    AddGroupStudent = 18,
    AddGroupTeacher = 19,
    GetStudentGroup = 20,
    CreateGroup = 21,
    UpdateGroup = 22,
    ListTeacherCourseGroups = 23,
    ListStudentCourseGroups = 24,
    CreateCourseHomework = 25,
    CreateGroupHomework = 26,
    UpdateDraftHomework = 27,
    PostponeHomeworkDeadlines = 28,
    PublishHomework = 29,
    ConfirmHomework = 30,
    GetStudentHomework = 31,
    GetTeacherHomework = 32,
    ListTeacherCourseHomeworks = 33,
    ListStudentCourseHomeworks = 34,
    UpdateSubmittedHomework = 35,
    DeleteSubmittedHomework = 36,
    DeleteSubmittedHomeworkFile = 37,
    GetSubmittedHomework = 38,
    ListAssignedReviews = 39,
    GetAssignedReview = 40
}
